export const FiguresInfo = [
  {
    category: "History",
    name: "Napoloen Bonaparte",
    title: "General",
    id: "history-napoleon",
    desc: "French general known for his military genius and for expanding France’s empire across Europe.",
    imgUrl: require("@/assets/images/figures/history-napoleon.png"),
  },
  {
    category: "History",
    name: "Genghis Khan",
    title: "Emperor",
    id: "history-khan",
    desc: "Mongol leader known for uniting nomadic tribes and founding the Mongol Empire, the largest contiguous land empire in history.",
    imgUrl: require("@/assets/images/figures/history-khan.png"),
  },
  {
    category: "History",
    name: "Alexander the Great",
    title: "Emperor",
    id: "history-alexander",
    desc: "Macedonian king known for his military brilliance and for creating one of the largest empires in ancient history by the age of 30.",
    imgUrl: require("@/assets/images/figures/history-alexander.png"),
  },
  {
    category: "History",
    name: "Julius Caesar",
    title: "General",
    id: "history-caesar",
    desc: "Roman general and statesman known for expanding the Roman Republic through military conquests and paving the way for the Roman Empire.",
    imgUrl: require("@/assets/images/figures/history-caesar.png"),
  },
  {
    category: "History",
    name: "Lee Soon Shin",
    title: "Emperor",
    id: "history-soon-shin",
    desc: "Korean naval commander known for his brilliant strategies and victories against Japanese forces.",
    imgUrl: require("@/assets/images/figures/history-soon-shin.png"),
  },
  {
    category: "Art",
    name: "Vincent Van Gogh",
    title: "Artist",
    id: "art-vincent",
    desc: "Dutch painter known for his expressive brushwork and emotional depth.",
    imgUrl: require("@/assets/images/figures/art-van-gogh.png"),
  },
  {
    category: "Art",
    name: "Frida Kahlo",
    title: "Artist",
    id: "art-kahlo",
    desc: "Mexican painter known for her vivid self-portraits and symbolic art that explored identity, pain, and Mexican culture.",
    imgUrl: require("@/assets/images/figures/art-kahlo.png"),
  },
  {
    category: "Art",
    name: "Salvador Dalí",
    title: "Artist",
    id: "art-dali",
    desc: "Spanish surrealist artist known for his dreamlike imagery and eccentric personality. ",
    imgUrl: require("@/assets/images/figures/art-dali.png"),
  },
  {
    category: "Art",
    name: "Pablo Picasso",
    title: "Artist",
    id: "art-picasso",
    desc: "Spanish artist known for co-founding Cubism and revolutionizing modern art with works that spanned styles from realism to abstraction.",
    imgUrl: require("@/assets/images/figures/art-picasso.png"),
  },
  {
    category: "Art",
    name: "Claude Monet",
    title: "Artist",
    id: "art-monet",
    desc: "French painter known as a founder of Impressionism, celebrated for his light-filled landscapes and series like Water Lilies.",
    imgUrl: require("@/assets/images/figures/art-monet.png"),
  },
  {
    category: "Sports",
    name: "Michael Jordan",
    title: "Athlete",
    id: "sports-jordan",
    desc: "American basketball player known for his unmatched skill, competitive spirit, and leading the Chicago Bulls to six NBA championships.",
    imgUrl: require("@/assets/images/figures/sports-jordan.png"),
  },
  {
    category: "Sports",
    name: "Muhammad Ali",
    title: "Athlete",
    id: "sports-ali",
    desc: "American boxer known for his exceptional skill, charisma, and activism, and widely regarded as one of the greatest athletes in history.",
    imgUrl: require("@/assets/images/figures/sports-ali.png"),
  },
  {
    category: "Sports",
    name: "Serena Williams",
    title: "Athlete",
    id: "sports-williams",
    desc: "American tennis champion known for her powerful game and 23 Grand Slam titles, making her one of the greatest in the sport’s history.",
    imgUrl: require("@/assets/images/figures/sports-williams.png"),
  },
  {
    category: "Sports",
    name: "Tom Brady",
    title: "Athlete",
    id: "sports-brady",
    desc: "American football quarterback known for his leadership and record seven Super Bowl wins, widely regarded as the greatest in NFL history.",
    imgUrl: require("@/assets/images/figures/sports-brady.png"),
  },
  {
    category: "Sports",
    name: "Kobe Bryant",
    title: "Athlete",
    id: "sports-bryant",
    desc: "American basketball player known for his skill, work ethic, and five NBA championships with the Los Angeles Lakers.",
    imgUrl: require("@/assets/images/figures/sports-bryant.png"),
  },
  {
    category: "Philosophy",
    name: "Friedrich Nietzsche",
    title: "Philosopher",
    id: "philosophy-nietzsche",
    desc: "German philosopher known for his critique of morality, religion, and his concept of the “will to power.”",
    imgUrl: require("@/assets/images/figures/philosophy-nietzsche.png"),
  },
  {
    category: "Philosophy",
    name: "Socrates",
    title: "Philosopher",
    id: "philosophy-socrates",
    desc: "Ancient Greek philosopher known for his method of questioning and for laying the foundation of Western philosophy.",
    imgUrl: require("@/assets/images/figures/philosophy-socrates.png"),
  },
  {
    category: "Philosophy",
    name: "Immanuel Kant",
    title: "Philosopher",
    id: "philosophy-kant",
    desc: "German philosopher known for his work in epistemology and ethics, especially the concept of the categorical imperative.",
    imgUrl: require("@/assets/images/figures/philosophy-kant.png"),
  },
  {
    category: "Philosophy",
    name: "Albert Camus",
    title: "Philosopher",
    id: "philosophy-camus",
    desc: "French-Algerian philosopher and writer known for his ideas on absurdism and works like The Stranger.",
    imgUrl: require("@/assets/images/figures/philosophy-camus.png"),
  },
  {
    category: "Philosophy",
    name: "Schopenhauer",
    title: "Philosopher",
    id: "philosophy-schopenhauer",
    desc: "German philosopher known for his pessimistic worldview and emphasis on the role of will in human suffering.",
    imgUrl: require("@/assets/images/figures/philosophy-schopenhauer.png"),
  },
  {
    category: "Literature",
    name: "William Shakespeare",
    title: "Poet",
    id: "literature-shakespeare",
    desc: 'English playwright and poet known for his profound influence on literature through works like "Hamlet" and "Romeo and Juliet".',
    imgUrl: require("@/assets/images/figures/literature-shakespeare.png"),
  },
  {
    category: "Literature",
    name: "Leo Tolstoy",
    title: "Novelist",
    id: "literature-tolstoy",
    desc: 'Russian novelist known for epic works like "War and Peace", exploring morality, history, and human nature.',
    imgUrl: require("@/assets/images/figures/literature-tolstoy.png"),
  },
  {
    category: "Literature",
    name: "Ernest Hemingway",
    title: "Novelist",
    id: "literature-hemingway",
    desc: "American writer known for his concise style and novels like The Old Man and the Sea.",
    imgUrl: require("@/assets/images/figures/literature-hemingway.png"),
  },
  {
    category: "Literature",
    name: "George Orwell",
    title: "Novelist",
    id: "literature-orwell",
    desc: 'British writer known for his political critiques and dystopian novels like "1984" and "Animal Farm".',
    imgUrl: require("@/assets/images/figures/literature-orwell.png"),
  },
  {
    category: "Literature",
    name: "Mark Twain",
    title: "Writer",
    id: "literature-twain",
    desc: 'American author and humorist known for "The Adventures of Huckleberry Finn" and his sharp social commentary.',
    imgUrl: require("@/assets/images/figures/literature-twain.png"),
  },
  {
    category: "Christianity",
    name: "C.S. Lewis",
    title: "Novelist",
    id: "christianity-lewis",
    desc: 'British writer and Christian apologist known for "The Chronicles of Narnia" and theological works like "Mere Christianity".',
    imgUrl: require("@/assets/images/figures/christianity-lewis.png"),
  },
  {
    category: "Christianity",
    name: "Apostle Paul",
    title: "Apostle",
    id: "christianity-paul",
    desc: "Early Christian missionary and theologian known for spreading Christianity and writing much of the New Testament.",
    imgUrl: require("@/assets/images/figures/christianity-paul.png"),
  },
  {
    category: "Christianity",
    name: "Augustine of Hippo",
    title: "Philosopher",
    id: "chistianity-augustine",
    desc: 'Early Christian theologian and philosopher known for shaping Western Christianity through works like "Confessions".',
    imgUrl: require("@/assets/images/figures/chistianity-augustine.png"),
  },
  {
    category: "Politics",
    name: "Nelson Mandela",
    title: "Politician",
    id: "politics-mandela",
    desc: "South African leader known for his fight against apartheid and for becoming the country’s first Black president.",
    imgUrl: require("@/assets/images/figures/politics-mandela.png"),
  },
  {
    category: "Politics",
    name: "Winston Churchill",
    title: "British statesman",
    id: "politics-churchill",
    desc: "British Prime Minister known for his leadership during World War II and his stirring speeches.",
    imgUrl: require("@/assets/images/figures/politics-churchill.png"),
  },
  {
    category: "Politics",
    name: "John F. Kennedy",
    title: "Politician",
    id: "politics-kennedy",
    desc: "American president known for his inspiring vision, Cold War leadership, and tragic assassination.",
    imgUrl: require("@/assets/images/figures/politics-kennedy.png"),
  },
  {
    category: "Politics",
    name: "Theodore Roosevelt",
    title: "Politician",
    id: "politics-roosevelt",
    desc: "American president known for his progressive reforms, strong leadership, and conservation efforts.",
    imgUrl: require("@/assets/images/figures/politics-roosevelt.png"),
  },
  {
    category: "Science",
    name: "Albert Einstein",
    title: "Physicist",
    id: "science-einstein",
    desc: "German-born physicist known for developing the theory of relativity and revolutionizing modern physics.",
    imgUrl: require("@/assets/images/figures/science-einstein.png"),
  },
  {
    category: "Science",
    name: "Marie Curie",
    title: "Scientist",
    id: "science-curie",
    desc: "Polish-French scientist known for pioneering research on radioactivity and winning two Nobel Prizes.",
    imgUrl: require("@/assets/images/figures/science-curie.png"),
  },
  {
    category: "Science",
    name: "Carl Sagan",
    title: "Astronomer",
    id: "science-sagan",
    desc: "American astronomer and science communicator known for popularizing science through works like Cosmos.",
    imgUrl: require("@/assets/images/figures/science-sagan.png"),
  },
  {
    category: "Science",
    name: "Richard Feynman",
    title: "Physicist",
    id: "science-feynman",
    desc: "American physicist known for his work in quantum electrodynamics and for making science accessible with his engaging lectures.",
    imgUrl: require("@/assets/images/figures/science-feynman.png"),
  },
];
